baseURL = "https://blog.burtonr.dev/"
languageCode = "en-us"
title = "BurtonR"
theme = "agency-blog"
paginate = 8

[params.navigation]
  brand = "BurtonR"
  posts = "Posts"
  tags = "Tags"

[[menu.postpend]]
  name = "burtonr"
  weight = 100
  url = "https://burtonr.dev"

[params.hero]
  title = "BurtonR Blog"
  subtitle = "Thoughts and opinions for future me, and hopefully others as well"

[params.posts]
  enable = true
  title = "Posts"
  url = "/posts/"
[params.tags]
  enable = true
  title = "Tags"
  url = "/tags/"

# TODO: Future update to display social/contact links
# [params]
#   github = "burtonr"
#   gitlab = "burtonr"
#   twitter = "_burtonr"
#   linkedin = "burtonrheutan"
#   email = "burton@rheutan.dev"
