baseURL = "https://blog.burtonr.dev/"
languageCode = "en-us"
title = "BurtonR"
theme = "hugo-dusk"
paginate = 10

[author]
  name = "Burton"

[params]
  description = "BurtonR thoughts and opinions for my future self, and others."
  github = "burtonr"
  gitlab = "burtonr"
  twitter = "_burtonr"
  linkedin = "burtonrheutan"
  email = "burton@rheutan.dev"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    weight = 20
    identifier = "tag"
    url = "/tags/"

# TODO: 'About' on the blog site, or just link to burtonr.dev???
#  [[menu.main]]
#    identifier = "about"
#    name = "about"
#    title = "about"
#    url = "/about/"
#    weight = 20
[permalinks]
  posts = "/:title/"